### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by ZhanYiLiangRan** [zhaomaoniu/nonebot-plugin-tsugu-frontend#3]
![1520039b6e82648694c1713eae102bd3](https://github.com/user-attachments/assets/aa14ed86-f47c-4c07-8bc8-a0592925acc2)
已安装pip install nonebot-plugin-tsugu-frontend

**Comment by zhaomaoniu** [comment]
推荐使用比本项目更完善的 [nonebot-plugin-tsugu-bangdream-bot](https://github.com/WindowsSov8forUs/nonebot-plugin-tsugu-bangdream-bot)
